MedicalEmergency/MedicalEmergency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('website.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MedicalEmergency/api/urls.py
from django.urls import path
from . import views

app_name = 'api'


urlpatterns = [
    path('register/', views.Register.as_view(), name='api-register'),
    path('login/', views.Login.as_view(), name='api-login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('productView/<uuid:product_id>', views.ProductView.as_view(), name='product-view'),
    path('meeting/', views.JoinMeet.as_view(), name='join-meeting'),
    path('bloodDonation/', views.Blood_Donation.as_view(), name='blood-donation'),
]

MedicalEmergency/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.Index.as_view(), name='dashboard'),
    path('medicine_order/', views.MedicineOrder.as_view(), name='medicine_order'),
    path('blood_donation/', views.BloodDonation.as_view(), name='blood_donation'),
    path('doctor_appointment/', views.DoctorAppointment.as_view(), name='doctor_appointment'),
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('forgot_password/', views.ForgotPassword.as_view(), name='forgot_password'),
    path('product_view/<uuid:product_id>', views.ProductView.as_view(), name='product_view'),
]

MedicalEmergency/templates/blood_donation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Blood-Donation{% endblock %}

{% block body %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Blood Donation</h1>
    <a href="{% url 'website:dashboard' %}" class="d-none d-sm-inline-block btn btn-secondary shadow-sm"><i
            class="fas fa-arrow-left fa-sm text-white-50"></i> Go back</a>
</div>

<!-- Content Row -->
<form action="{% url 'api:blood-donation' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="inputname4">Full-Name</label>
        <input name="name" type="text" class="form-control" id="inputname4" placeholder="name">
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputMobile">Mobile</label>
            <input name="mobile" type="number" class="form-control" id="inputMobile">
        </div>
        <div class="form-group col-md-4">
            <label for="inputBlood">Blood-group</label>
            <select name="blood_group" id="inputBlood" class="form-control">
              <option value="A+" selected>A+</option>
              <option value="A-">A-</option>
              <option value="B+">B+</option>
              <option value="B-">B-</option>
              <option value="AB+">AB+</option>
              <option value="AB-">AB-</option>
              <option value="O+">O+</option>
              <option value="O-">O-</option>
            </select>
          </div>
    </div>
    <div class="form-group">
        <label for="inputAddress">Address</label>
        <input name="address" type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputCity">City</label>
            <input name="city" type="text" class="form-control" id="inputCity">
        </div>
        <div class="form-group col-md-4">
            <label for="inputState">State</label>
            <input name="state" type="text" class="form-control" id="inputState">
        </div>
        <div class="form-group col-md-2">
            <label for="inputZip">Pin</label>
            <input name="pin" type="text" class="form-control" id="inputZip">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

MedicalEmergency/templates/doctors_appointment.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Doctor's-Appointment{% endblock %}


{% block body %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Doctor's appointment</h1>
    <a href="{% url 'website:dashboard' %}" class="d-none d-sm-inline-block btn btn-secondary shadow-sm"><i
            class="fas fa-arrow-left fa-sm text-white-50"></i> Go back</a>
</div>

<!-- Content Row -->
<div class="table-responsive mailbox-messages">
    <table class="table table-hover table-striped">
        <tbody>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <label for="check1"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Unaib Saiyad</a></td>
                <td class="mailbox-subject"><b>Dentist</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"></td>
                <td class="mailbox-date">
                    <button class="btn-success btn">Available</button>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <label for="check2"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star-o text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">
                    <button class="btn btn-success" disabled>Available</button>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check3">
                        <label for="check3"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star-o text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">11 hours ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check4">
                        <label for="check4"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"></td>
                <td class="mailbox-date">15 hours ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check5">
                        <label for="check5"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">Yesterday</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check6">
                        <label for="check6"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star-o text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">2 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check7">
                        <label for="check7"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star-o text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">2 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check8">
                        <label for="check8"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"></td>
                <td class="mailbox-date">2 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check9">
                        <label for="check9"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"></td>
                <td class="mailbox-date">2 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check10">
                        <label for="check10"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star-o text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"></td>
                <td class="mailbox-date">2 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check11">
                        <label for="check11"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star-o text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">4 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check12">
                        <label for="check12"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"></td>
                <td class="mailbox-date">12 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check13">
                        <label for="check13"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star-o text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">12 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check14">
                        <label for="check14"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">14 days ago</td>
            </tr>
            <tr>
                <td>
                    <div class="icheck-primary">
                        <input type="checkbox" value="" id="check15">
                        <label for="check15"></label>
                    </div>
                </td>
                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a>
                </td>
                <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                <td class="mailbox-subject"><b>AdminLTE 3.0 Issue</b> - Trying to find a solution to
                    this problem...
                </td>
                <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                <td class="mailbox-date">15 days ago</td>
            </tr>
        </tbody>
    </table>
    <!-- /.table -->
</div>

<nav aria-label="...">
    <ul class="pagination">
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
    </ul>
  </nav>

{% endblock %}

MedicalEmergency/templates/forgot-password.html
{% extends 'login_base.html' %}
{% load static %}

{% block title %}
Forgot-Password
{% endblock %}

{% block body %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                    <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                        and we'll send you a link to reset your password!</p>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <input type="email" class="form-control form-control-user"
                                            id="exampleInputEmail" aria-describedby="emailHelp"
                                            placeholder="Enter Email Address...">
                                    </div>
                                    <a href="login.html" class="btn btn-primary btn-user btn-block">
                                        Reset Password
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'website:register' %}">Create an Account!</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'website:login' %}">Already have an account? Login!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

MedicalEmergency/templates/login.html
{% extends 'login_base.html' %}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block body %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <form class="user">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="email" class="form-control form-control-user"
                                            id="email" aria-describedby="emailHelp"
                                            placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user"
                                            id="password" placeholder="Password">
                                    </div>
                                    <a id="submit-login" class="btn btn-primary btn-user btn-block">
                                        Login
                                    </a>
                                    <div class="d-flex justify-content-center">
                                        <div id="hidden-load-submit" class="spinner-grow text-primary d-none" role="status">
                                            <span class="sr-only">Loading...</span>
                                        </div>
                                    </div>
                                    <hr>
                                    <hr>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'website:forgot_password' %}">Forgot Password?</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'website:register' %}">Create an Account!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/login.js' %}"></script>
{% endblock %}

MedicalEmergency/templates/login_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Medical Emergency - {% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}

</head>

<body class="bg-gradient-primary">

    {% block body %}{% endblock %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    {% block script %}{% endblock %}

</body>

</html>

MedicalEmergency/templates/medicine_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Medicine-Order{% endblock %}

{% block style %}
    <style>
                  .col-md-3
          {
          display: inline-block;
          margin-left:-4px;
          }

          .carousel-indicators .active {
          background-color: blue;
            }

          .col-md-3 img{

          width: 200px;
          height: 300px;
          }

          body .carousel-indicator li{
          background-color: blue;
          }

          body .carousel-indicators{
          bottom: 0;
          }

          body .carousel-control-prev-icon,
          body .carousel-control-next-icon{
          background-color: blue;
          }
           body .no-padding{
           padding-left: 0;
           padding-right: 0;
           }
    </style>
 {% endblock %}


{% block body %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Medicine order</h1>
    <a href="{% url 'website:dashboard' %}" class="d-none d-sm-inline-block btn btn-secondary shadow-sm"><i
            class="fas fa-arrow-left fa-sm text-white-50"></i> Go back</a>
</div>

<!-- Content Row -->
{% for product in products %}
{% if product %}
<h4 class="h4 text-gray-900 p-3">{{product.0.category}} medicines</h4>
<div id="carouselExampleDark{{forloop.counter}}" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark{{forloop.counter}}" data-bs-slide-to="0"
            class="active" aria-current="true" aria-label="Slide 1"></button>
        {% for slide in slides %}
        {% if forloop.counter == forloop.parentloop.counter %}
            {% for n in slide %}
            <button type="button" data-bs-target="#carouselExampleDark{{forloop.counter}}" data-bs-slide-to="{{n}}"
            class="" aria-current="true" aria-label="Slide {{n}}"></button>
        {% endfor %}
        {% endif %}
        {% endfor %}
    </div>
    <div class="container carousel-inner no-padding row">

        <div class="carousel-item active row">
          <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="card" style="width: 15rem;">
              <img src='{{product.0.image.url}}' class="card-img-top" alt="...">
              <div class="card-body">
                  <h5 class="card-title">{{product.0.product_name}}</h5>
                  <p class="card-text">{{product.0.desc|slice:"0:20"}}</p>
                  <button onclick="productView('{{product.0.product_id}}')" class="btn btn-primary">Buy Now</button>
              </div>
            </div>
         </div>
  
  
          {% for i in product|slice:"1:"%}
          <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="card" style="width: 15rem;">
              <img src='{{i.image.url}}' class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{i.product_name}}</h5>
                <p class="card-text">{{i.desc}}</p>
                <button onclick="productView('{{i.product_id}}')" class="btn btn-primary">Buy Now</button>
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:3 and forloop.counter > 0 and not forloop.last %}
        </div><div class="carousel-item">
          {% endif %}
  
          {% endfor %}
      </div>

    <button style="z-index: -1;" class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark{{forloop.counter}}"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button style="z-index: -1;" class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark{{forloop.counter}}"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endif %}
{% endfor %}

{% endblock %}

{% block script %}
<script src="{% static 'js/medicine_order.js' %}"></script>
{% endblock %}

MedicalEmergency/templates/register.html
{% extends 'login_base.html' %}
{% load static %}

{% block body %}

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                        </div>
                        <form class="user" id="register-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control form-control-user" id="username"
                                    placeholder="Enter Username">
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control form-control-user" id="email"
                                    placeholder="Email Address">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control form-control-user" id="full-name"
                                    placeholder="Enter Fullname">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control form-control-user" id="address"
                                    placeholder="Parmanent Address">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="password" class="form-control form-control-user" id="password"
                                        placeholder="Password">
                                </div>
                                <div class="col-sm-6">
                                    <input type="number" class="form-control form-control-user" id="mobile"
                                        placeholder="Mobile number">
                                </div>
                            </div>
                            <a id="submit-register" class="btn btn-primary btn-user btn-block">
                                Register Account
                            </a>
                            <div class="d-flex justify-content-center">
                                <div id="hidden-load-submit" class="spinner-grow text-primary d-none" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>
                            <hr>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="{% url 'website:forgot_password' %}">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{% url 'website:login' %}">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/register.js' %}"></script>
{% endblock %}